set -g default-terminal "tmux-256color"
set-option -as terminal-features ",xterm-256color:RGB"
set-option -as terminal-overrides ",xterm-256color:Tc"
set -g default-command "${SHELL} --login"
set -sg escape-time 10
